Change power-menu to lowercase

diff --git a/rofi/scripts/rofi-power-menu b/rofi/scripts/rofi-power-menu
--- a/rofi/scripts/rofi-power-menu
+++ b/rofi/scripts/rofi-power-menu
@@ -229,6 +229,6 @@ else
         fi
     done
     # The selection didn't match anything, so raise an error
-    echo "Invalid selection: $selection" >&2
+    echo "invalid selection: $selection" >&2
     exit 1
 fi
